(function(O) {
  'use strict';
  const {V,State:S,Geometry:G,Design:D,Simulation:Sim}=O;
  const assert=(condition,message)=>{if(!condition)throw Error(message);};
  const near=(a,b,tol=1e-10)=>assert(Math.abs(a-b)<=tol,`${a} differs from ${b}; tolerance ${tol}`);
  const angle=(a,b)=>Math.atan2(V.len(V.cross(a,b)),V.dot(a,b));
  const mirror=(over={})=>({id:'mirror',center:[0,0,0],normal:[0,0,1],width:20,height:20,focal:0,type:'reflect',reflectivity:.9,twoSided:false,...over});
  function fixture(){const s=S.defaults();s.source={...s.source,kind:'point',position:[0,0,8],axis:[0,0,-1],distribution:'cone',angle:35};s.target={...s.target,center:[0,0,30],aim:[0,0,30],width:120,height:120,resolution:50};s.envelope={kind:'box',center:[0,0,0],size:[40,40,40]};s.surfaces=[mirror()];s.simulation.rays=5000;return s;}
  const run=s=>new Sim(s,{paths:0}).finish();
  const tests=[];const add=(name,fn)=>tests.push({name,fn});
  add('01 · Mirror tilt doubles beam deflection',()=>{const d=[0,0,-1],base=V.reflect(d,[0,0,1]),samples=[];for(const deg of [1,5,17,32]){const a=deg*Math.PI/180,out=V.reflect(d,[Math.sin(a),0,Math.cos(a)]);near(angle(base,out),2*a,1e-12);samples.push(`${deg}° → ${(angle(base,out)*180/Math.PI).toFixed(9)}°`);}return samples.join('; ');});
  add('02 · Bisector aim lands on the requested point',()=>{let worst=0;for(const p of [[3,4,-8],[-7,2,-12],[12,-6,-4],[.1,1,-17]]){const source=[-2,3,1],target=[4,-2,45],n=D.aim(p,source,target),out=V.reflect(V.unit(V.sub(p,source)),n),hit=G.targetHit({center:target,normal:[0,0,-1],width:1000,height:1000},p,out,1e-12);assert(hit,'No target hit');worst=Math.max(worst,V.distance(hit.p,target));}assert(worst<1e-11,`Miss ${worst}`);return `Largest centre-ray miss ${worst.toExponential(3)} units.`;});
  add('03 · Reflection law and unit outgoing direction',()=>{let worst=0;for(let i=1;i<90;i++){const t=i*Math.PI/180,d=[Math.sin(t),0,-Math.cos(t)],out=V.reflect(d,[0,0,1]);worst=Math.max(worst,Math.abs(angle(V.mul(d,-1),[0,0,1])-angle(out,[0,0,1])));near(V.len(out),1,1e-12);}assert(worst<1e-12,'Angular mismatch');return `89 incidence angles; max error ${worst.toExponential(3)} rad.`;});
  add('04 · Snell, Fresnel and total internal reflection',()=>{const a=30*Math.PI/180,d=[Math.sin(a),0,-Math.cos(a)],x=O.snell(d,[0,0,1],1,1.5);near(Math.sin(a),1.5*x.d[0],1e-12);near(O.snell([0,0,-1],[0,0,1],1,1.5).R,.04,1e-12);const critical=Math.asin(1/1.5),below=O.snell([Math.sin(critical-.01),0,Math.cos(critical-.01)],[0,0,1],1.5,1),above=O.snell([Math.sin(critical+.01),0,Math.cos(critical+.01)],[0,0,1],1.5,1);assert(!below.tir&&above.tir,'Critical-angle branch incorrect');near(above.R,1);return `sin θ₁ = n₂ sin θ₂; normal reflectance ${x.R.toFixed(6)} at 30°; critical angle ${(critical*180/Math.PI).toFixed(6)}°.`;});
  add('05 · Nearest-hit occlusion, with shadower removed',()=>{const s=fixture();s.surfaces=[mirror({id:'front',center:[0,0,3],type:'absorb'}),mirror({id:'behind'})];const a=run(s);assert(a.hits[0]>0&&a.hits[1]===0,`Hits ${a.hits}`);s.surfaces.shift();const b=run(s);assert(b.hits[0]>0,'Control still dark');return `Behind: ${a.hits[1]} hits with shadower; ${b.hits[0]} without.`;});
  add('06 · Mirror back face absorbs',()=>{const s=fixture();s.surfaces[0].normal=[0,0,-1];const a=run(s);near(a.ledger.via,0);assert(a.ledger.absorbed>0,'Back face did not absorb');s.surfaces[0].twoSided=true;const b=run(s);assert(b.ledger.via>0,'Explicit two-sided control failed');return `One-sided target ${a.ledger.via}; explicit two-sided ${b.ledger.via.toFixed(6)}.`;});
  add('07 · Energy conservation with multiple bounces',()=>{const s=fixture();s.simulation.bounces=6;s.surfaces.push(mirror({id:'ceiling',center:[0,0,12],normal:[0,0,-1],width:12,height:12}));const a=run(s),l=a.ledger,accounted=l.target+l.absorbed+l.escaped+l.unresolved;near(accounted,l.emitted,1e-10);assert(l.absorbed>0&&l.unresolved>0,'Fixture failed to exercise losses and truncation');return JSON.stringify({...l,error:accounted-l.emitted});});
  add('08 · Byte-identical determinism, order and JSON round-trip',()=>{const s=fixture();s.surfaces.push(mirror({id:'small',center:[10,0,-2],width:6,height:6}));const a=run(s),b=run(S.clone(s)),c=run({...s,surfaces:[...s.surfaces].reverse()});const hashes=[a,b,c].map(x=>O.hashGrid(x.grid));assert(new Set(hashes).size===1,hashes.join(' ≠ '));assert(a.grid.every((x,i)=>Object.is(x,b.grid[i])),'Float bytes differ');const restored=S.validate(S.clone(s));assert(O.hashGrid(run(restored).grid)===hashes[0],'Validated load differs');return `original / repeat / reordered / restored: ${hashes[0]}`;});
  add('09 · Source-image scaling and facet-footprint limit',()=>{const s=fixture(),target={...s.target,center:[0,0,20],width:200,height:200},facet=G.surface(mirror({width:10,height:10}),0);function image(xs,xf){const start=[xs,0,10],p=[xf,0,0],d=V.unit(V.sub(p,start)),hit=G.intersect(facet,start,d);assert(hit,'Expected mirror intersection');return G.targetHit(target,hit.p,V.reflect(d,hit.n),1e-12).p[0];}
    const widths=[.25,.5,1,2].map(w=>Math.abs(image(w/2,0)-image(-w/2,0)));for(let i=0;i<widths.length;i++)near(widths[i],[.25,.5,1,2][i]*2,1e-11);const apertureWidths=[2,1,.1,.001].map(w=>Math.abs(image(0,w/2)-image(0,-w/2)));for(let i=0;i<apertureWidths.length;i++)near(apertureWidths[i],[2,1,.1,.001][i]*3,1e-11);assert(apertureWidths.at(-1)<target.width/target.resolution,'Point-source footprint did not collapse below a cell');return `Source widths ×2 magnification: ${widths.join(', ')}. Point-source aperture widths ×(1+2): ${apertureWidths.join(', ')}.`;});
  add('10 · Revolved parabola collimates better than a flat aperture',()=>{const s=fixture();s.source.position=[0,0,0];s.envelope={kind:'box',center:[0,0,0],size:[40,40,40]};s.design.budget=128;const f=5,R=12;s.profile=Array.from({length:41},(_,i)=>{const r=R*i/40;return [r,r*r/(4*f)-f];});D.profileMesh(s);const root=G.tree(s.surfaces.map(G.surface));let squares=0,flatSquares=0,spot=0,flatSpot=0,count=0;
    for(let j=0;j<300;j++){const rng=new O.RNG(j+7),r=R*.92*Math.sqrt(rng.next()),a=rng.next()*Math.PI*2,p=[r*Math.cos(a),r*Math.sin(a),r*r/(4*f)-f],d=V.unit(p),h=G.nearest(root,[0,0,0],d,1e-10);if(!h)continue;const out=V.reflect(d,h.n),flat=V.reflect(V.unit([p[0],p[1],-f]),[0,0,1]);squares+=angle(out,[0,0,1])**2;flatSquares+=angle(flat,[0,0,1])**2;const hit=G.targetHit({center:[0,0,100],normal:[0,0,-1],width:10000,height:10000},h.p,out,1e-10);spot+=hit.p[0]**2+hit.p[1]**2;const fh=G.targetHit({center:[0,0,100],normal:[0,0,-1],width:10000,height:10000},[p[0],p[1],-f],flat,1e-10);flatSpot+=fh.p[0]**2+fh.p[1]**2;count++;}
    const rms=Math.sqrt(squares/count),rmsFlat=Math.sqrt(flatSquares/count);assert(count>290,'Too few profile intersections');assert(rms<.04&&rms<rmsFlat/10,`Divergence ${rms} / ${rmsFlat}`);assert(spot<flatSpot/20,'Spot did not tighten');return `${count} actual mesh hits: RMS divergence ${(rms*180/Math.PI).toFixed(3)}° vs flat ${(rmsFlat*180/Math.PI).toFixed(3)}°; target RMS radius ${Math.sqrt(spot/count).toFixed(3)} vs ${Math.sqrt(flatSpot/count).toFixed(3)}.`;});
  add('11 · Whole-scene scale invariance',()=>{const s=fixture();s.source.kind='planar';s.source.size=.6;s.surfaces[0].focal=6;const a=run(s),b=S.clone(s),k=10;for(const name of ['position'])b.source[name]=V.mul(b.source[name],k);b.source.size*=k;b.source.height*=k;b.envelope.center=V.mul(b.envelope.center,k);b.envelope.size=V.mul(b.envelope.size,k);for(const name of ['center','aim'])b.target[name]=V.mul(b.target[name],k);b.target.width*=k;b.target.height*=k;for(const f of b.surfaces){f.center=V.mul(f.center,k);f.width*=k;f.height*=k;f.focal*=k;}const c=run(b);assert(O.hashGrid(a.grid)===O.hashGrid(c.grid),'Scaling changed cell allocation');return `1× and 10× grid hash ${O.hashGrid(a.grid)}; epsilon scales with scene size.`;});
  add('12 · Allocator interception under envelope expansion',()=>{const s=S.defaults();s.design.budget=32;s.simulation.rays=10000;S.paintPreset(s);const values=[];let previous=0;for(const scale of [.6,.8,1,1.2,1.4,1.8,2.5]){s.envelope.size=V.mul([30,26,22],scale);D.generate(s);const efficiency=run(s).stats().intercepted;assert(efficiency>=previous,`Expanded envelope reduced interception: ${previous} → ${efficiency} at ${scale}×`);values.push(`${scale}×: ${(efficiency*100).toFixed(2)}%`);previous=efficiency;}return `Same 10,000 emission samples; retained feasible incumbents: ${values.join('; ')}. Finite-sample guarantee, not a proof of the global optimum.`;});
  add('13 · Asymmetric enclosure uses variable-radius geometry',()=>{const s=S.defaults();s.source.position=[-12,-9,-2];s.source.axis=V.unit([1,.3,-.8]);s.envelope={kind:'box',center:[2,4,-14],size:[32,42,34]};s.design.budget=64;S.paintPreset(s);D.generate(s);assert(s.surfaces.length>20,'Too few surfaces');const centers=s.surfaces.map(f=>f.center),radii=centers.map(p=>V.distance(p,s.source.position)),b=G.bounds(centers),span=V.sub(b.max,b.min),ratio=Math.max(...radii)/Math.min(...radii);assert(ratio>1.7,`Radius ratio ${ratio} resembles a shell`);assert(span[1]>s.envelope.size[1]*.3&&span[2]>s.envelope.size[2]*.3,`Insufficient span ${span}`);assert(s.surfaces.every(f=>G.fits(s.envelope,f)),'Facet exceeds enclosure');return `${s.surfaces.length} facets; radii ${Math.min(...radii).toFixed(2)}–${Math.max(...radii).toFixed(2)}; XYZ span ${span.map(x=>x.toFixed(2))}. Equal-path candidate family, not proof of the globally best half-parabola.`;});
  add('14 · Each mode responds through the shared UI reducer',()=>{const hashes=[];for(const mode of ['paint','stamp','profile']){const s=S.defaults();s.mode=mode;s.simulation.rays=6000;s.design.budget=24;S.paintPreset(s);s.stamps=[{id:'a',u:.5,v:.5,size:5}];if(mode==='profile')D.parabolaProfile(s);else D.generate(s);const a=O.hashGrid(run(s).grid);if(mode==='paint'){S.edit(s,'design.curved',false);D.generate(s);}else if(mode==='stamp'){S.edit(s,'design.stampSize',12);s.stamps[0].size=s.design.stampSize;D.generate(s);}else{S.edit(s,'design.profileSweep','extrude');D.profileMesh(s);}const b=O.hashGrid(run(s).grid);assert(a!==b,`${mode} control inert (${a})`);hashes.push(`${mode}: ${a} → ${b}`);}return hashes.join('; ');});
  add('15 · Impossible fine features name a quantitative constraint',()=>{const s=S.defaults();s.source.size=8;s.target.resolution=100;s.design.budget=16;S.paintPreset(s,'spot');D.generate(s);const notes=s.notes.filter(n=>n.kind==='limit');assert(notes.some(n=>n.text.includes('Minimum feature')&&/\d/.test(n.text)),'Missing quantitative source-image limit');assert(notes.some(n=>n.text.includes('Étendue')),'Missing area/angle warning');return notes.map(n=>n.text).join('\n');});
  add('16 · Zero reflectivity, direct component and emission axis',()=>{const s=fixture();s.surfaces[0].reflectivity=0;const a=run(s);near(a.ledger.via,0);s.source.axis=[0,0,1];s.source.angle=10;const b=run(s);assert(b.ledger.direct>.99,'Direct target component missing');s.source.axis=[0,0,-1];const c=run(s);assert(c.ledger.direct===0,'Backward axis ignored');return `ρ=0 reflected=${a.ledger.via}; forward direct=${b.ledger.direct.toFixed(6)}; reverse direct=${c.ledger.direct}.`;});
  add('17 · Curved surface intersection satisfies its equation',()=>{const f=G.surface(mirror({focal:5,width:12,height:12}),0);let error=0;for(let i=-5;i<=5;i++)for(let j=-5;j<=5;j++){const h=G.intersect(f,[i,j,20],[0,0,-1]);assert(h,'Missed sag');error=Math.max(error,Math.abs(h.p[2]-(i*i+j*j)/20));}assert(error<1e-12,'Not an exact paraboloid');return `121 intersections; maximum sag residual ${error.toExponential(3)}.`;});
  add('18 · Emission sampling matches solid-angle laws',()=>{const means=[];for(const law of ['lambertian','cone','gaussian']){const s=S.defaults().source;s.distribution=law;s.kind='point';s.axis=V.unit([1,-2,-3]);s.angle=40;const em=new O.Emitter(s),rng=new O.RNG(911);let m=0;for(let i=0;i<20000;i++){const r=em.sample(rng);near(V.len(r.d),1,1e-12);m+=V.dot(r.d,s.axis);}m/=20000;if(law==='lambertian')assert(Math.abs(m-2/3)<.01,`cosine mean ${m}`);if(law==='cone')assert(Math.abs(m-(1+Math.cos(40*Math.PI/180))/2)<.01,`cone mean ${m}`);means.push(`${law}: mean cosθ ${m.toFixed(5)}`);}return means.join('; ');});
  add('19 · Closed lens boundaries and Fresnel energy balance',()=>{const summary=[];for(const kind of ['plano','biconvex','fresnel','tir']){const s=S.defaults();s.source.kind='point';s.source.axis=[0,0,1];s.source.distribution='cone';s.source.angle=25;s.envelope={kind:'box',center:[0,0,15],size:[50,50,50]};s.design.lens=kind;s.design.budget=24;s.simulation.rays=3000;s.simulation.bounces=8;assert(D.lens(s),'Lens did not fit');const mesh=s.surfaces.map(G.surface),root=G.tree(mesh),h=G.nearest(root,[0,0,0],[0,0,1],1e-8);assert(h&&V.dot(h.n,[0,0,1])<0,`${kind} entrance normal wrong`);const a=run(s),l=a.ledger;near(l.emitted,l.target+l.absorbed+l.escaped+l.unresolved,1e-10);assert(l.refracted>0,`${kind} transmits no light to target`);summary.push(`${kind}: ${mesh.length} triangles, target ${(l.target*100).toFixed(2)}%, unresolved ${(l.unresolved*100).toFixed(2)}%`);}return summary.join('\n');});
  add('20 · Performance: 10,000 rays / 200 surfaces / 3 bounces',()=>{const s=fixture();s.simulation.rays=10000;s.simulation.bounces=3;s.source.angle=80;s.surfaces=[];for(let i=0;i<200;i++){const x=(i%10-4.5)*3,y=(Math.floor(i/10)-9.5)*3;s.surfaces.push(mirror({id:'bench-'+i,center:[x,y,0],width:3,height:3}));}run({...s,simulation:{...s.simulation,rays:1000}});const start=performance.now(),a=run(s),wall=performance.now()-start;assert(wall<500,`Measured ${wall.toFixed(2)} ms exceeds 500 ms`);return `Measured ${wall.toFixed(2)} ms including construction; tracing ${a.ms.toFixed(2)} ms; ${a.surfaces.length} surfaces, ${a.done} rays, cap ${s.simulation.bounces}. No browser/render time included.`;});
  add('21 · Curved image conjugates and finite-source magnification',()=>{
    const a=10,b=20,f=a*b/(a+b),facet=G.surface(mirror({focal:f}),0),target={center:[0,0,b],normal:[0,0,-1],width:100,height:100};
    const land=(sourceX,apertureX)=>{const p=[apertureX,0,apertureX*apertureX/(4*f)],source=[sourceX,0,a],d=V.unit(V.sub(p,source)),h=G.intersect(facet,source,d,1e-12);return G.targetHit(target,h.p,V.reflect(d,h.n),1e-12).p[0];};
    const h=1e-4,m=(land(h,0)-land(-h,0))/(2*h),apertureDerivative=(land(0,h)-land(0,-h))/(2*h);near(m,-f/(a-f),1e-9);assert(Math.abs(apertureDerivative)<1e-8,`Conjugate aperture derivative ${apertureDerivative}`);
    return `f=${f.toFixed(6)}, a=${a}, b=${b}: measured source magnification ${m}; aperture derivative ${apertureDerivative.toExponential(3)}. Uses actual curved hits.`;
  });
  add('22 · Stamp scale range is active and floor is enforced',()=>{
    const s=S.defaults();s.mode='stamp';s.design.budget=24;s.simulation.rays=30000;s.stamps=[{id:'a',u:.5,v:.5,size:.1}];D.generate(s);const low=s.stamps[0].size;assert(low>.1&&s.stamps[0].clamped,'Impossible width was not clamped');
    const samples=[];for(const size of [low,low+1,10,18]){s.stamps[0].size=size;D.generate(s);samples.push({size:s.stamps[0].size,hash:O.hashGrid(run(s).grid)});}assert(new Set(samples.map(x=>x.hash)).size===samples.length,'A displayed stamp scale was inert');return JSON.stringify(samples);
  });
  function one(t){const start=performance.now();try{return {name:t.name,pass:true,detail:t.fn(),ms:performance.now()-start};}catch(e){return {name:t.name,pass:false,detail:e.message,ms:performance.now()-start};}}
  O.Checks={tests,run:()=>tests.map(one),async runAsync(onRow){const out=[];for(const t of tests){await new Promise(resolve=>setTimeout(resolve,0));const r=one(t);out.push(r);onRow?.(r);}return out;}};
})(Optics);
