// concatenate the dev modules into ONE self-contained solver file.  Every module sees a private RF (reads fall through to the app's, writes stay inside).
const fs = require('fs'), path = require('path');
const DISH = process.argv.includes('--dish'), IDEAL = process.argv.includes('--ideal'), argv = process.argv.slice(2).filter((a) => a !== '--dish' && a !== '--ideal');       // the variant flag goes on the file's PRIVATE RF (globalThis here is the sandbox): a bare `RF.` would set it on the app's RF and leak into every SQM file loaded later.  --dish: the second solver (any base shell) from the same sources; --ideal: the ideal beam shaped from the ideal-beam goals (dev/ideal.js)
const order = ['fwd', 'target', 'plan', 'sqm', 'emit'].concat(DISH ? ['shell'] : [], ['pipeline'], IDEAL ? ['ideal'] : [], ['solver-main']);
const parts = order.map((n) => `// ============================================================ ${n}\n` + fs.readFileSync(path.join(__dirname, 'dev', n + '.js'), 'utf8'));
const header = fs.readFileSync(path.join(__dirname, 'dev', DISH ? 'HEADER-dish.txt' : IDEAL ? 'HEADER-ideal.txt' : 'HEADER.txt'), 'utf8');
const out = header + '\n(function (globalThis) {\n' + (DISH ? "globalThis.RF.SqmVariant = 'dish';\n" : IDEAL ? "globalThis.RF.SqmVariant = 'ideal';\n" : '') + parts.join('\n') + `\n})(Object.assign(Object.create(globalThis), { RF: Object.create(globalThis.RF) }));\n`;
try { new (require('vm').Script)(out, { filename: 'sqm-hl (built)' }); } catch (e) { console.error('BUILD REFUSED: the output does not compile —', e.stack.split('\n').slice(0, 4).join(' | ')); process.exit(1); }   // a syntax error is otherwise silent: the app's loader skips a file that does not load
const dest = path.resolve(__dirname, '..', '..', 'solvers', argv[0] || (DISH ? 'sqm-hl-dish.js' : IDEAL ? 'sqm-hl-ideal.js' : 'sqm-hl.js')); fs.writeFileSync(dest, out); const dbg = path.join(__dirname, 'build'); fs.mkdirSync(dbg, { recursive: true }); fs.writeFileSync(path.join(dbg, (DISH ? 'sqm-hl-dish' : IDEAL ? 'sqm-hl-ideal' : 'sqm-hl') + (process.env.SQM_TAG ? '.' + process.env.SQM_TAG : '') + '.debug.js'), out.replace('RF.SqmSolver = {', '(0, eval)("this").__sqm = RF; RF.SqmSolver = {')); console.log('built', dest, out.length, 'bytes,', out.split('\n').length, 'lines');
